version: "3.7"

services:
  db_service:
    container_name: db_container
    env_file:
      - .env
    image: postgres:12.3
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - "5432"

  nginx_service:
    container_name: nginx_container
    build: ./nginx
    ports:
      - 8000:80
    volumes:
      - static_data:/usr/src/app/staticfiles
    depends_on:
      - web_service

  web_service:
    container_name: web_container
    env_file:
      - .env
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - "8000"
    depends_on:
      - db_service
    volumes:
      - static_data:/usr/src/app/staticfiles
    environment:
      - POSTGRES_HOST=db_container

volumes:
  db_data:
  static_data:
