# Generated by Django 2.2 on 2019-05-18 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                )
            ],
        ),
        migrations.CreateModel(
            name="Priority",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Enter Priority Title", max_length=50),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Enter Shift Date",
                        unique=True,
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="shifts.Manager",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Enter Status Title", max_length=50),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "title",
                    models.CharField(help_text="Enter Task Title", max_length=50),
                ),
                (
                    "start",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="Enter Start Time"
                    ),
                ),
                (
                    "end",
                    models.DateTimeField(
                        blank=True, help_text="Enter End Time", null=True
                    ),
                ),
                (
                    "handler",
                    models.ForeignKey(
                        help_text="Enter Member Id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="shifts.Member",
                    ),
                ),
                (
                    "priority",
                    models.ForeignKey(
                        help_text="Enter Priority Id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shifts.Priority",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        help_text="Enter Shift Id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="shifts.Shift",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        help_text="Enter Status Id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shifts.Status",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="member",
            name="shifts",
            field=models.ManyToManyField(related_name="members", to="shifts.Shift"),
        ),
        migrations.AddField(
            model_name="member",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
