# Generated by Django 2.0.6 on 2018-08-21 20:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter Task Title', max_length=50)),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('shift', models.ForeignKey(help_text='Enter Shift Id', on_delete=django.db.models.deletion.CASCADE, to='shifts.Shift')),
            ],
        ),
    ]
